name: CI
on: [push]
jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Test
        run: npm test
